language: ruby
rvm:
- 2.0.0
- 2.1.3
- 2.1.5
- 2.2.0
- 2.2.1
- 2.2.2
env:
  global:
  - secure: JyafUsGzHEXaouwqpRbrkyqdOQypTV4OoljDX8aSbGRZQq5yElvrB6WonAijAO8VaJGzNs1B/QV+3Uw0zULU6S0qVgtHccScKze0cMNNQCV9Y2iysyG2cYrPBh4mqMSpB0A4titTPXUvAxCtsMKUs87NzLHGHSOtDJR1JX9n7g0=
  - secure: EfbT6TFaldH4rNxo3reCzLZvjbujCN8FHr4AxSYX5gDCUaaWFe5gUiz6vwS1bk5AKZSt8mSUsIwMH1EmcB1VjZTYeQbSTyIU5FqKlbtTi8cJGURMyDB90ROb6j/OBftnIvoze+ONXACVhsA9OFinoqihibUVlymdAgSAoPwRDoE=
deploy:
  provider: rubygems
  gem: factor-connector-hipchat
  api_key:
    secure: mMY5ZBtkbojnbXBLCnMpvdokLoJU+RbeafrQ3CZpOGXK4+mg8hoY79kdNIYNImF4bhOh3G0Ol0ByCsBGcciX1hknWLyrv8ZNNxlhoDLgTozcTIi8Zyd1SkRD360LUxGn5cDOgX+7o226zh6p2B742dVcgIf8Y469cGxT855DpBg=
  on:
    tags: true
    all_branches: true
